### ISSUE TITLE
[CI] [Report] Errors from 1.5 all plugins test 

### ISSUE THREAD

**Issue by purbon** [logstash-plugins/logstash-filter-alter#4]
Seen: http://build-eu-00.elastic.co/view/LS%201.5/job/Logstash_1.5_All_Plugins_test/772/console

```
 2) LogStash::Filters::Alter condrewrite with dynamic values "{"rewrite-me":"%{test}"}" when processed
     Failure/Error: insist { subject["rewrite-me"] } == "%{rewrite-value}"
     RuntimeError:
       expected UTF-8 encoding for value=%{rewrite-value}, encoding=#<Encoding:US-ASCII>
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:264:in `validate_value'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/spec_helper.rb:40:in `[]='
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:131:in `condrewrite'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:116:in `condrewrite'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:107:in `filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:163:in `multi_filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:160:in `multi_filter'
     # (eval):33:in `filter_func'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:301:in `filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:49:in `results'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:47:in `results'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:58:in `subject'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/spec/filters/alter_spec.rb:43:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist.rb:47:in `value'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/comparators.rb:13:in `=='
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/spec/filters/alter_spec.rb:43:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  3) LogStash::Filters::Alter condrewrite with dynamic values "{"rewrite-me":"hello","test":"hello"}" when processed
     Failure/Error: insist { subject["rewrite-me"] } == "%{rewrite-value}"
     RuntimeError:
       expected UTF-8 encoding for value=%{rewrite-value}, encoding=#<Encoding:US-ASCII>
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/event.rb:264:in `validate_value'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/spec_helper.rb:40:in `[]='
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:131:in `condrewrite'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:116:in `condrewrite'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/lib/logstash/filters/alter.rb:107:in `filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:163:in `multi_filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/filters/base.rb:160:in `multi_filter'
     # (eval):33:in `filter_func'
     # ./vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:301:in `filter'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:49:in `results'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:47:in `results'
     # ./vendor/bundle/jruby/1.9/gems/logstash-devutils-0.0.15-java/lib/logstash/devutils/rspec/logstash_helpers.rb:58:in `subject'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/spec/filters/alter_spec.rb:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist.rb:47:in `value'
     # ./vendor/bundle/jruby/1.9/gems/insist-1.0.0/lib/insist/comparators.rb:13:in `=='
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-alter-0.1.6/spec/filters/alter_spec.rb:47:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

Is this plugin going to be deprecated and removed? if so, I guess we can just follow up and exclude it from the tests. Makes sense?
